### ISSUE TITLE
Merge splitted tiles with land an sea vs Tiles 131/90 - java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by bappppp** [treee111/wahooMapsCreator#198]
Hello,

Thank for your dev, your project is very usefull.

## Expected Behavior
No error :)

## Current Behavior
Error with the tile 131/90 : "'_Exception in thread "pool-2-thread-1" java.lang.OutOfMemoryError: GC overhead limit exceeded'_'" 

## Steps to Reproduce the Issue
My goal is to add some tags (drinking_water, bakery, picnic_table, toilets, & camp_site) directly in my bolt v2 (for a France's map). So i customize _tags-to-keep.json_ and _tag-wahoo.xml_.
Next i launch the program : "_python -m wahoomc cli -xy 131/90 -tag tag-wahoo.xml -v_"
After some processing, i've an error.

## Context
 * OS/Platform: Windows

## Log Output / Stack Trace
```
INFO:--------------------------------------------------------------------------------
INFO:# Merge splitted tiles with land an sea
INFO:+ Coordinates: 131,90 (1 of 1)
DEBUG:--------------------------------------------------------------------------------
DEBUG:# Sorting land* osm files
DEBUG:subprocess:'avr. 10, 2023 10:50:13 AM org.openstreetmap.osmosis.core.Osmosis run'
DEBUG:subprocess:'INFOS: Osmosis Version 0.48.3'
DEBUG:subprocess:'avr. 10, 2023 10:50:13 AM org.openstreetmap.osmosis.core.Osmosis run'
DEBUG:subprocess:'INFOS: Preparing pipeline.'
DEBUG:subprocess:'avr. 10, 2023 10:50:13 AM org.openstreetmap.osmosis.core.Osmosis run'
DEBUG:subprocess:'INFOS: Launching pipeline execution.'
DEBUG:subprocess:'avr. 10, 2023 10:50:13 AM org.openstreetmap.osmosis.core.Osmosis run'
DEBUG:subprocess:'INFOS: Pipeline executing, waiting for completion.'
DEBUG:subprocess:'avr. 10, 2023 10:50:14 AM org.openstreetmap.osmosis.core.Osmosis run'
DEBUG:subprocess:'INFOS: Pipeline complete.'
DEBUG:subprocess:'avr. 10, 2023 10:50:14 AM org.openstreetmap.osmosis.core.Osmosis run'
DEBUG:subprocess:'INFOS: Total execution time: 749 milliseconds.'
DEBUG:+ Sorting land* osm files: OK
DEBUG:subprocess:'avr. 10, 2023 10:50:14 AM org.openstreetmap.osmosis.core.Osmosis run'
DEBUG:subprocess:'INFOS: Osmosis Version 0.48.3'
DEBUG:subprocess:'avr. 10, 2023 10:50:14 AM org.openstreetmap.osmosis.core.Osmosis run'
DEBUG:subprocess:'INFOS: Preparing pipeline.'
DEBUG:subprocess:'avr. 10, 2023 10:50:14 AM org.openstreetmap.osmosis.tagtransform.impl.TransformLoader parseTranslation'
DEBUG:subprocess:'INFOS: New translation: Adjust tunnel Layers'
DEBUG:subprocess:'avr. 10, 2023 10:50:14 AM org.openstreetmap.osmosis.core.Osmosis run'
DEBUG:subprocess:'INFOS: Launching pipeline execution.'
DEBUG:subprocess:'avr. 10, 2023 10:50:14 AM org.openstreetmap.osmosis.core.Osmosis run'
DEBUG:subprocess:'INFOS: Pipeline executing, waiting for completion.'
DEBUG:subprocess:'Exception in thread "pool-2-thread-1" java.lang.OutOfMemoryError: GC overhead limit exceeded'
DEBUG:subprocess:'at org.openstreetmap.osmosis.core.domain.v0_6.TagCollectionImpl.<init>(TagCollectionImpl.java:27)'
DEBUG:subprocess:'at org.openstreetmap.osmosis.core.domain.v0_6.CommonEntityData.<init>(CommonEntityData.java:78)'
DEBUG:subprocess:'at org.openstreetmap.osmosis.core.domain.v0_6.CommonEntityData.<init>(CommonEntityData.java:56)'
DEBUG:subprocess:'at org.openstreetmap.osmosis.pbf2.v0_6.impl.PbfBlobDecoder.processNodes(PbfBlobDecoder.java:198)'
DEBUG:subprocess:'at org.openstreetmap.osmosis.pbf2.v0_6.impl.PbfBlobDecoder.processOsmPrimitives(PbfBlobDecoder.java:348)'
DEBUG:subprocess:'at org.openstreetmap.osmosis.pbf2.v0_6.impl.PbfBlobDecoder$$Lambda$3/1115071557.accept(Unknown Source)'
DEBUG:subprocess:'at java.util.Optional.ifPresent(Unknown Source)'
```

Thank for your helps, i can give you more informations if you need.
Or tell me, if i'm doing wrong :)

BR,

**Comment by bappppp** [comment]
Hello,

Ok, my knowledge is too limited to understand. But i can fix this issue by lauching the command "set JAVACMD_OPTIONS=-server -Xmx2G" before your tool.

Thanks again for your tool. He is very usefull !

BR,

**Comment by treee111** [comment]
Hi @bappppp,
nice that you found the solution by yourself! I didn't know that one can launch this command prior to execution of wahooMapsCreator.
I added this possibility to the FAQ: https://github.com/treee111/wahooMapsCreator/blob/develop/docs/FAQ.md#i-have-a-java-error-java-heap-space---out-of-memory

In 3. I have described a permanent soution, in both ways you could as well have `-Xmx3G` to allocate even more memory for java.

Thanks for your kind words, I am happy you use the tool! 👍
