### ISSUE TITLE
Consider switching to pyhgtmap (fork) for contour lines

### ISSUE THREAD

**Issue by quietvoid** [treee111/wahooMapsCreator#217]
## Is your feature request related to a problem? Please describe.

The latest `phyghtmap` release does not work very well with latest Python and `matplotlib` versions.
Someone forked it into [pyhgtmap](https://github.com/agrenott/pyhgtmap) however wahoomc has a hardcoded binary to `phyghtmap`.

## Describe the solution you'd like

A way to specify the binary, or maybe setting the default used binary to the new fork while having a fallback to the old version.

## Describe alternatives you've considered

Currently I just made a symbolic link, `pyhgtmap` seems to have backwards compatibility and I was able to create a map.

Unfortunately I think it's not Windows compatible yet: https://github.com/agrenott/pyhgtmap/issues/7

**Comment by treee111** [comment]
I also had this error now while trying your fork in Windows due to the linked issue.
As reference for others, this is how it looks like when crashing:
```Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\anaconda3\envs\gdal-dev-pyh\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\<username>\AppData\Local\anaconda3\envs\gdal-dev-pyh\lib\runpy.py", line 86, in _run_code     
    exec(code, run_globals)
  File "C:\Users\<username>\AppData\Local\anaconda3\envs\gdal-dev-pyh\Scripts\pyhgtmap.exe\__main__.py", line 4, in <module>
  File "C:\Users\<username>\AppData\Local\anaconda3\envs\gdal-dev-pyh\lib\site-packages\pyhgtmap\main.py", line 12, in <module>
    from pyhgtmap.hgt.processor import HgtFilesProcessor
  File "C:\Users\<username>\AppData\Local\anaconda3\envs\gdal-dev-pyh\lib\site-packages\pyhgtmap\hgt\processor.py", line 3, in <module>
    from multiprocessing.context import ForkProcess
ImportError: cannot import name 'ForkProcess' from 'multiprocessing.context' (C:\Users\<username>\AppData\Local\anaconda3\envs\gdal-dev-pyh\lib\multiprocessing\context.py)
```

**Comment by treee111** [comment]
Hi @quietvoid,
thanks for pointing to the fork `pyhgtmap`! It's a good idea since phyghtmap is difficult to install.

Windows support seams like a blocker for me, so we would have a different tool per OS. With the downsides of enhancing and making documentation more difficult, maybe equalness of results, ...
Supporting both tools for macOS with a switch or "if pyhgtmap is there use it, fallback on phyghtmap" would also have identical downsindes in my opinion.

However I tried it and it works for me on macOS. Feel free to try out the changes in #234 and if it works on your device.

**Comment by quietvoid** [comment]
Thanks. I haven't tested but the code looks like it would work.
I don't mind sticking to symbolic links, it works with the current wahoomc code.

**Comment by billux** [comment]
I recently use your PR to use pyhgtmap to workarround https://github.com/treee111/wahooMapsCreator/issues/243#issuecomment-2828508041.

But I run into a ImportError when calling pyhgtmap. The issue has been reported here: https://github.com/agrenott/pyhgtmap/issues/60. The solution is to downgrade the phx-class-registry depencency:

```console
$ pip install phx-class-registry==4.1.0
```
FYI I run Arch Linux and wahoomc and its dependencies are installed under a Conda environment.

I was then able to generate tiles with elevation data.

Thanks for your work!
