### ISSUE TITLE
Can't get countour line generation to work (Error "No module found names 'matplotlib')

### ISSUE THREAD

**Issue by tarmacalastair** [treee111/wahooMapsCreator#263]
## Expected Behaviour
Generate maps with contour lines

## Current Behaviour
Error "No module found names 'matplotlib'

## Steps to Reproduce the Issue

1. Follow the instructions at https://github.com/treee111/wahooMapsCreator/blob/develop/docs/QUICKSTART_ANACONDA.md. All steps completed successfully up to the end of https://github.com/treee111/wahooMapsCreator/blob/develop/docs/QUICKSTART_ANACONDA.md#additional-programs-for-generating-contour-lines (where phyghtmap seems to install successfully) 
2. At https://github.com/treee111/wahooMapsCreator/blob/develop/docs/QUICKSTART_ANACONDA.md#verify-phyghtmap I issue the command:
`phyghtmap`
The following message appears
```
(gdal-user) al@Latitude-E7440:~/phyghtmap-2.23$ phyghtmap
Traceback (most recent call last):
  File "/usr/local/bin/phyghtmap", line 33, in <module>
    sys.exit(load_entry_point('phyghtmap==2.23', 'console_scripts', 'phyghtmap')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/phyghtmap", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/local/lib/python3.12/dist-packages/phyghtmap-2.23-py3.12.egg/phyghtmap/main.py", line 17, in <module>
  File "/usr/local/lib/python3.12/dist-packages/phyghtmap-2.23-py3.12.egg/phyghtmap/hgt.py", line 10, in <module>
ModuleNotFoundError: No module named 'matplotlib'
```

3. If I then try to run `python -m wahoomc cli -co isle-of-man -nbc -con` then I get the same message (as above) at the end just as it starts to generate the contour lines, followed by one extra line: `ERROR:! Error in phyghtmap with tile: 124,81. Win_macOS/elevation`

## Context
 * OS/Platform: `Ubuntu Linux 24.04`
 * Other information regarding your environment *(optional)*: `nothing`

Many thanks. I'm looking forward to trying to generate some maps with contours and POIs.

## Log Output / Stack Trace

```
{...}
```

**Comment by Ebe66** [comment]
Maybe you can install it manually with something like pip install mathplotlib 
I don't really know if this works like this in Anaconda. I do know you need to install an older version for it to work but I can't find what version is installed on my system...
