### ISSUE TITLE
Error with GUI on Mac OS

### ISSUE THREAD

**Issue by assofour** [treee111/wahooMapsCreator#29]
python3 wahoo_map_creator.py

Select 'asia', then....

`Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/Users/edwardwang/Documents/Code/wahooMapsCreator/common_resources/input.py", line 212, in callback_continent
    self.cb_country["values"] = ast.literal_eval('constants.' + continent.replace("-", ""))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ast.py", line 99, in literal_eval
    return _convert(node_or_string)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ast.py", line 98, in _convert
    return _convert_signed_num(node)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ast.py", line 75, in _convert_signed_num
    return _convert_num(node)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ast.py", line 66, in _convert_num
    _raise_malformed_node(node)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ast.py", line 63, in _raise_malformed_node
    raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: <_ast.Attribute object at 0x7fb6b826fa60>`

**Comment by treee111** [comment]
Hi!
thanks for reaching out!
I gonna have a look into this and if I am able to reproduce.

**Comment by treee111** [comment]
Hi @assofour,
I corrected the cause of the error and published a new version: 0.8.1.

I would be happy if you could double-check if the error is not occuring anymore - thanks! :)

**Comment by assofour** [comment]
I will try to test it and get back to you ASAP.

Ed

From: Benjamin K. ***@***.***>
Date: Friday, September 10, 2021 at 7:16 PM
To: treee111/wahooMapsCreator ***@***.***>
Cc: assofour ***@***.***>, Mention ***@***.***>
Subject: Re: [treee111/wahooMapsCreator] Error with GUI on Mac OS (#29)

Hi @assofour<https://github.com/assofour>,
I corrected the cause of the error and published a new version: 0.8.1.

I would be happy if you could double-check if the error is not occuring anymore - thanks! :)

**Comment by assofour** [comment]
> Hi @assofour,
> I corrected the cause of the error and published a new version: https://github.com/treee111/wahooMapsCreator/releases/tag/v0.8.1.
> 
> I would be happy if you could double-check if the error is not occuring anymore - thanks! :)

This version works as I expected. I can select continent/country properly without error. Good job.

**Comment by treee111** [comment]
> > Hi @assofour,
> > I corrected the cause of the error and published a new version: https://github.com/treee111/wahooMapsCreator/releases/tag/v0.8.1.
> > I would be happy if you could double-check if the error is not occuring anymore - thanks! :)
> 
> This version works as I expected. I can select continent/country properly without error. Good job.

thank you for checking instantly, cheers! :-)
