### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'osmium': 'osmium'

### ISSUE THREAD

**Issue by bka-git** [treee111/wahooMapsCreator#95]
Hi,

## Expected Behavior
according to the documentation, map for example austria should be created with this command:

python wahoo_map_creator.py austria

## Current Behavior
Unfortunately, on a fresh installed Ubuntu (Ubuntu 21.10) buil fails with following error message:

```
python wahoo_map_creator.py austria
+ Input country or json file: austria.

# Read json file
+ Use json file /home/bka/Downloads/common_resources/json/europe/austria.json with 19 tiles
# Read json file: OK

# check land_polygons.shp file
# check land_polygons.shp file: OK

# check countries .osm.pbf files
+ Checking for old maps and remove them
+ mapfile for austria: up-to-date. Input: austria.
# Check countries .osm.pbf files: OK

# Filter tags from country osm.pbf files
+ Create filtered country file for austria
Traceback (most recent call last):
  File "wahoo_map_creator.py", line 41, in <module>
    oOSMmaps.filter_tags_from_country_osm_pbf_files()
  File "/home/bka/Downloads/common_python/osm_maps_functions.py", line 197, in filter_tags_from_country_osm_pbf_files
    result = subprocess.run(cmd, check=True)
  File "/home/bka/Downloads/envs/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/bka/Downloads/envs/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/bka/Downloads/envs/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'osmium': 'osmium'

```

## Context
 * OS/Platform:
```
 lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
```
 * conda
```
conda -V
conda 4.10.3
```
 * python
```
python3 -V
Python 3.7.11
```

**Comment by treee111** [comment]
Hi!

thanks for reaching out!
`osmium` might be missing on your computer and lead to that error.

Some questions:

- Did you follow the Quickstart Anaconda Setup?
- Did you install `osmium-tool` manually as well as the other ones mentioned in that chapter? 
  - https://github.com/treee111/wahooMapsCreator/blob/develop/docs/QUICKSTART_ANACONDA.md#macos-linux-only
- what happens if you enter that in your terminal?
```
osmium version
```

**Comment by treee111** [comment]
Hi @bka-git,
did you succeed? Any update on this?
Greetings

**Comment by treee111** [comment]
closing due to inactivity
